### ISSUE TITLE
Error trying compile for Ubuntu 20.10 and Hasura 1.3.3

### ISSUE THREAD

**Issue by eamigo86** [melehin/graphql-engine-arm64#1]
Hi, first of all, thank you very much for your contribution. I have a Raspberry Pi4 on which I am trying to install Hasura and I have run into this [issue](https://github.com/hasura/graphql-engine/issues/1266). But when I try to compile graphql_engine v1.3.3 for ubuntu 20.10, I get this error:

![image](https://user-images.githubusercontent.com/11740026/103557705-e3080c00-4eb3-11eb-8e79-3fd69612ab18.png)

This error occurs in this Dockerfile line:
`RUN make deps server-build`

Could you provide some tips from your experience to resolve it? Thanks in advance

**Comment by melehin** [comment]
Hi! 

I think you have not enough free disk space.
Anyway you can use ready to use docker image [fedormelexin/graphql-engine-arm64](https://hub.docker.com/repository/docker/fedormelexin/graphql-engine-arm64)
