### ISSUE TITLE
v2.0.0 cli-migrations images

### ISSUE THREAD

**Issue by nikhilshinday** [melehin/graphql-engine-arm64#10]
Hi there! Thanks so much for maintaining these @melehin :) I was pleasantly surprised to see v2.0.0 within hours of it launching this morning! 

For some reason, the `v2.0.0-beta.<x>-cli-migration-<y>` images are erroring on start and it has something to do with [this](https://github.com/hasura/graphql-engine/issues/7058) issue. I'm wondering if you're planning on building `cli-migration`-tagged docker containers for the v2.0.0 production release? 

I'm running on an M1 right now, let me know if I can help - I'm unclear on how to build the `cli-migrations` images from looking at the Dockerfile in this repo, if you clarify, happy to run the build for `cli-migrations-v2` and `v3`!

**Comment by nikhilshinday** [comment]
I should've read the readme before the Dockerfile - building the cli-migrations version now

**Comment by nikhilshinday** [comment]
reopening this. I ran the following script: 
```
export DOCKER_USERNAME=nikhilshinday
export HASURA_VERSION=v2.0.0
export SCRIPT_VERSION=v2

docker build \                                                                                           ─╯
    --build-arg SCRIPT_VERSION=${SCRIPT_VERSION} \
    --build-arg SERVER_IMAGE_TAG=${HASURA_VERSION} \
    --build-arg SERVER_IMAGE=${DOCKER_USERNAME}/graphql-engine-arm64 \
    -t "${DOCKER_USERNAME}/graphql-engine-arm64:v${HASURA_VERSION}.cli-migrations-${SCRIPT_VERSION}" .
```
and got the following error during build:
```
#19 50.47 Installing library in /root/.cabal/lib/aarch64-linux-ghc-8.10.2/network-2.7.0.0-3mn9xGtsjxP2D45jECDEbO
#19 50.61 Registering library for network-2.7.0.0..
#19 50.61
#19 50.61 Downloading HTTP-4000.3.14...
#19 50.62   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
#19 50.62                                  Dload  Upload   Total   Spent    Left  Speed
100 72938    0 72938    0     0   112k      0 --:--:-- --:--:-- --:--:--  112k
#19 51.28   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
#19 51.28                                  Dload  Upload   Total   Spent    Left  Speed
100  5843    0  5843    0     0  13878      0 --:--:-- --:--:-- --:--:-- 13878
#19 51.78 [1 of 1] Compiling Main             ( Setup.lhs, Setup.o )
#19 51.83 You are using an unsupported version of LLVM!
#19 51.83 Currently only 9 is supported. System LLVM version: 10.0.0
#19 51.83 We will try though...
#19 51.88 Linking Setup ...
#19 53.26 collect2: error: ld returned 1 exit status
#19 53.26 `gcc' failed in phase `Linker'. (Exit code: 1)
#19 53.28
#19 53.28 Error during cabal-install bootstrap:
#19 53.28 Compiling the Setup script failed.
------
executor failed running [/bin/sh -c bash ./bootstrap.sh]: exit code: 2
```

thoughts?

**Comment by melehin** [comment]
Hi, @nikhilshinday!

It building now.

> reopening this. I ran the following script:
you forgot to change directory to cli-migrations before and did try to build v2.0.0 image, not cli-migrations. and forgot to change branch i think.

**Comment by melehin** [comment]
I stopped the building of cli-migrations for v2.0.0 due issue above and will build later
I'm building v2.0.1 and cli-migrations right now

**Comment by melehin** [comment]
Hi, @nikhilshinday!

Could you check new cli-migrations image for v2.0.1?

**Comment by nikhilshinday** [comment]
sorry for not responding sooner -- checked it out and things look good to go :) thank you so much!
