### ISSUE TITLE
pg_dump throws an error.

### ISSUE THREAD

**Issue by cassus** [melehin/graphql-engine-arm64#11]
Hi, thanks so much for maintaining an arm build!

This issue is related to https://github.com/melehin/graphql-engine-arm64/issues/2 (pg_dump throws an error. Can't run migrations.)

When try to use the `http://localhost:8080/v1alpha1/pg_dump` endpoint
I get this response
```
{"path":"$","error":"error while executing pg_dump: Warning: No existing cluster is suitable as a default target. Please see man pg_wrapper(1) how to specify one.\nError: You must install at least one postgresql-client-<version> package\n","code":"unexpected"}
```

Running `apt install -y postgresql-client-12` in the container fixes the problem.

Can you include this package in your image?

**Comment by melehin** [comment]
Hi, @cassus!

Which version of the image did you use?

**Comment by cassus** [comment]
Ohh, yes, sorry. Forgot to mention that.

`fedormelexin/graphql-engine-arm64:v2.0.1`

**Comment by melehin** [comment]
It's very strange because there is postgresql-client-13 (not 12) in the Dockerfile. Maybe it doesn't have backward compatibility.
https://github.com/melehin/graphql-engine-arm64/blob/5096de371885d282557532dc358681760b56a259/Dockerfile#L61

**Comment by cassus** [comment]
I just removed the local image and re-downloaded `fedormelexin/graphql-engine-arm64:v2.0.1`

```
# apt list --installed | grep postgresql-client

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

postgresql-client-common/bionic-pgdg,now 226.pgdg18.04+1 all [installed]
```

I don't see postgresql-client-13 installed

**Comment by cassus** [comment]
Maybe postgresql-client-13 couldn't install?

If I run this I get an error
```
# apt-get install postgresql-client-13
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 postgresql-client-13 : Depends: libreadline7 (>= 6.0) but it is not installable
E: Unable to correct problems, you have held broken packages.
```

**Comment by melehin** [comment]
Your are right!

This issue related to https://stackoverflow.com/a/63299329/7678391
I added a version to this line from env var and building v2.0.3 now. If it gets installed I will update v2.0.1 and v2.0.2
```Dockerfile
RUN echo "deb http://apt.postgresql.org/pub/repos/apt bionic-pgdg main ${PG_CLIENT_VER}" > /etc/apt/sources.list.d/pgdg.list
```

**Comment by cassus** [comment]
Can I help with the testing?

**Comment by melehin** [comment]
@cassus
Yes, please, if you can. I will notify you when i done.
I got some unexpected errors with dependencies related to libmysqlclient-dev and libghc-pcre-light-dev packages which were added in the latest versions. I added these deps and building images now.

**Comment by melehin** [comment]
@cassus

Could you test fedormelexin/graphql-engine-arm64:v2.0.3 image?

**Comment by mirzap** [comment]
> @cassus
> 
> Could you test fedormelexin/graphql-engine-arm64:v2.0.3 image?

hi @melehin, there's not yet `v2.0.3` image. Can you push the build pls?

**Comment by melehin** [comment]
hi @mirzap 

i am building it now after i found and fixed one issue. 
v2.0.3 image will available today after 3-4 hours i think.

**Comment by melehin** [comment]
@mirzap and @cassus 
Fixed image on dockerhub

**Comment by cassus** [comment]
Thanks @melehin!

I checked and the pg_dump api endpoint works with v2.0.3

```
image: fedormelexin/graphql-engine-arm64:v2.0.3
```
