### ISSUE TITLE
graphql-engine installed with docker-compose fails to start

### ISSUE THREAD

**Issue by Proxiweb** [melehin/graphql-engine-arm64#13]
Hello,
I'm trying to run hasura on a rasperry pi 4 8GB. It fails to start... I can't figure what's going on.

docker logs on **fedormelexin/graphql-engine-arm64** gives me the message **standard_init_linux.go:228: exec user process caused: exec format error**
The postgresql image is running without problem.

**Comment by melehin** [comment]
Hi, @Proxiweb!

Can you share **uname -a** output here?
Also check [this comment](https://github.com/melehin/graphql-engine-arm64/issues/3#issuecomment-843368260)

**Comment by Proxiweb** [comment]
Thanks ! I have a clear path to fix this now. Thanks also for this quick response and for having built this.
