### ISSUE TITLE
v2.0.10.cli-migrations-v2 is missing

### ISSUE THREAD

**Issue by flobaader** [melehin/graphql-engine-arm64#15]
Hi,

thanks for the amazing work! I have found out that the docker tag `docker.io/fedormelexin/graphql-engine-arm64:v2.0.10.cli-migrations-v2` is missing.

Could you please check that out?

Thanks in advance,

Florian

**Comment by melehin** [comment]
Hi

This image is available now.
Something was wrong with my build script.
