### ISSUE TITLE
pg_dump throws an error. Can't run migrations.

### ISSUE THREAD

**Issue by pat154** [melehin/graphql-engine-arm64#2]
Hello. Thanks for this ARM build! It's a real life saver.

I'm on an M1 mac book. I've managed to get Hasura running with this image and I can run the Hasura CLI via rosetta.

When I try to run `pg_dump` through Hasura with `/v1alpha1/pg_dump` I get the following error:

```
{
    "path": "$",
    "error": "internal exception while executing pg_dump",
    "code": "unexpected"
}
```

I think this is also causing migrations with the Hasura CLI to fail.

When I run `pg_admin` directly in my Postgres docker container it works as expected.

Any insights into why this might be failing?

Thanks again!

**Comment by melehin** [comment]
Hi, @pat154!

Unfortunately, I didn't tested Hasura CLI on my docker images.
I think i forgot to add postgresql-client-common package as dependencies.

Could you run this cmd to install required dependencies and rerun migrations?
```bash
sudo docker exec -it 2629d32bc07e bash -c 'apt update && apt install -y postgresql-client-common'
```
Replace 2629d32bc07e to your Hasura's started container id

Let me know if it will work or not.

**Comment by pat154** [comment]
Thanks a lot for your reply! I managed to make some progress...

I installed `postgres-client-common` in the container. I then tried to run `/v1alpha1/pg_dump` via Hasura and got this error:
```
{
    "path": "$",
    "error": "error while executing pg_dump: Warning: No existing local cluster is suitable as a default target. Please see man pg_wrapper(1) how to specify one.\nError: You must install at least one postgresql-client-<version> package\n",
    "code": "unexpected"
}
```
Once I also installed `postgres-client-12` I managed to get `pg_dump` to run successfully.

However, the Hasura CLI still doesn't function correctly. When I run `hasura migrate create "init" --admin-secret <admin secret>` the migration files are still empty.

Any more insights into what the issue may be? No errors are being thrown.

**Comment by MarcStdt** [comment]
@pat154 Thanks for sharing your solution.
I went into some more trouble bcs I am using postgres 13 and installing postgresql-client-13 in the container is not that straight forward, but after solving that, everything runs smooth and I can finally use pg_dump.
