### ISSUE TITLE
Error starting graphql-engine

### ISSUE THREAD

**Issue by mwarger** [melehin/graphql-engine-arm64#3]
When I try this image, I get the following error:

`ERROR: for graphql-engine Cannot start service graphql-engine: OCI runtime create failed: container_linux.go:370: starting container process caused: exec: "graphql-engine": executable file not found in $PATH: unknown`

Any thoughts on what could be the issue?  Is there something missing in my path that I need for it to run correctly?

Thanks!

**Comment by melehin** [comment]
Hi!

What command did you use to run?

**Comment by mwarger** [comment]
@melehin I have the image listed in my docker-compose file - it's setup the same as the example from the README.

**Comment by melehin** [comment]
Have you added "command: ..." inside docker-compose?

It should be like this (for docker-compose) or empty (as the example):
command: ["/srv/graphql-engine", "serve", "--console-assets-dir", "/srv/console-assets"]

**Comment by mwarger** [comment]
I did have command in there, and it wasn't formatted as your example is.  Looks like it worked for me.  Thank you so much!

**Comment by pie6k** [comment]
Could you push it to docker hub?

**Comment by melehin** [comment]
Hi, @pie6k!
Already on: https://hub.docker.com/r/fedormelexin/graphql-engine-arm64
Or do you mean push after last Dockerfile update?

**Comment by pie6k** [comment]
I mean last dockerfile update :)

**Comment by melehin** [comment]
Sure :)
It's building now on my rpi4,
after this is done i will notify you

**Comment by melehin** [comment]
Done.
Version v2.0.0-alpha.2 is building now, if successful, I will also send it to docker hub.

**Comment by melehin** [comment]
@go4cas i didn't used migrations before
I think i can make the arm64 image based on https://github.com/hasura/graphql-engine/tree/master/scripts/cli-migrations/v2
Also i should build hasura-cli from go sources for this image

**Comment by mwarger** [comment]
@melehin Just curious if you were able to create an arm64 image of `v2.0.0-alpha.5.cli-migrations-v2` tag?

**Comment by melehin** [comment]
@mwarger, @go4cas  I have successfully built cli-hasura-linux-arm64
but have stopped on https://github.com/hasura/graphql-engine/tree/master/scripts/cli-migrations/v2 (no free time yet)

![image](https://user-images.githubusercontent.com/3829167/113972948-f630cc00-9854-11eb-8056-01d37ab769b1.png)

cli-ext looks workable too

![image](https://user-images.githubusercontent.com/3829167/113973797-4fe5c600-9856-11eb-91ab-053faf380b2d.png)

**Comment by melehin** [comment]
@mwarger @go4cas 

Could you test it?
fedormelexin/graphql-engine-arm64:v2.0.0-alpha.7.cli-migrations-v2

**Comment by go4cas** [comment]
Thanks, @melehin. When using the new image, I get the following error: "ERROR: for nhost_hasura  Cannot start service nhost-graphql-engine: OCI runtime create failed: container_linux.go:367: starting container process caused: exec: "docker-entrypoint.sh": executable file not found in $PATH: unknown"

**Comment by melehin** [comment]
@go4cas I fixed it, try now.
repull it first: docker pull fedormelexin/graphql-engine-arm64:v2.0.0-alpha.7.cli-migrations-v2

**Comment by go4cas** [comment]
@melehin ... legend!! It works now. Thanks so much for this!

**Comment by mwarger** [comment]
@melehin 

I'm seeing a strange error that says the `hdb_catalog.hdb_role` table does not exist.  I have a migration that attempts to select from that table, which causes the error.  I'm not sure if this is relevant or not but I thought I'd post anyway.

I'm attempting to use the new migrations tag in this project in place of the stock version it uses. 
 https://github.com/hgiasac/hasura-typescript-boilerplate

**Comment by melehin** [comment]
@mwarger

Maybe because you were using hasura version 2.0.0- *, but the boilerplate requires 1.3.3 or the oldest version (I'm not sure). If you need other versions, let me know.

**Comment by mwarger** [comment]
@melehin Just a small update - I tried initializing a completely new project - no metadata to apply or anything, using a blank `hasura init` created project.  When starting the server with the `v2.0.0-alpha.7.cli-migrations-v2` I see the following error.  

Again, I'm not sure if this is useful or not - just wanted to record my issue.  If you or anyone sees this, it would be helpful to know if this can be recreated or if it's just me having this problem.  thanks for your help and for making the image updates!

```
{"type":"http-log","timestamp":"2021-04-09T03:01:47.122+0000","level":"info","detail":{"operation":{"query_execution_time":1.412208e-3,"user_vars":{"x-hasura-role":"admin"},"request_id":"6cb6febe-fd04-4984-a27e-143faa8bdcbc","response_size":89,"request_read_time":6.417e-6},"request_id":"6cb6febe-fd04-4984-a27e-143faa8bdcbc","http_info":{"status":200,"http_version":"HTTP/1.1","url":"/v1/metadata","ip":"127.0.0.1","method":"POST","content_encoding":"gzip"}}}
time="2021-04-09T03:01:48Z" level=fatal msg="failed to apply metadata: cannot apply metadata on the database: {\"path\":\"$\",\"error\":\"key \\\"tables\\\" not found\",\"code\":\"parse-failed\"}"
```

**Comment by mwarger** [comment]
@melehin I might have found something intersting - would you be able to make an image based on v3?  It seems there's a difference here between the v2 and v3 config migration images: 
v3: https://hasura.io/docs/latest/graphql/core/migrations/advanced/auto-apply-migrations.html
v2: https://hasura.io/docs/latest/graphql/core/migrations/config-v2/advanced/auto-apply-migrations.html#auto-apply-migrations-v2

I'm still picking away at this in my spare time, trying some different variations to figure out which variable is causing my issue.

**Comment by melehin** [comment]
@mwarger
fedormelexin/graphql-engine-arm64:v2.0.0-alpha.7.cli-migrations-v3

**Comment by mwarger** [comment]
@melehin Thank you, that one started right up for me.

**Comment by original0594** [comment]
@melehin Any chance you could create one for v1.3.3.cli-migrations ?

**Comment by melehin** [comment]
@original0594

fedormelexin/graphql-engine-arm64:v1.3.3.cli-migrations-v2
fedormelexin/graphql-engine-arm64:v1.3.3.cli-migrations-v3

**Comment by original0594** [comment]
@melehin thanks for the quick response/turnaround! Though i need a v1 config, so just graphql-engine:v1.3.3.cli-migrations

**Comment by melehin** [comment]
@original0594 
I switched to tag v1.3.3 and i got 1.3.3-dirty version of hasura cli as result of compilation
I can build an image based on this version.

**Comment by melehin** [comment]
@original0594

Could you try this version:
fedormelexin/graphql-engine-arm64:v1.3.3.cli-migrations (based on scripts for v1.3.3 version and latest hasura cli)

**Comment by original0594** [comment]
@melehin fails over same as the amd64 image, after starting graphql-engine it fails before apply migrations
```
graphql-engine_1           | {"timestamp":"2021-04-16T19:55:34.000+0000","level":"info","type":"startup","detail":{"kind":"migrations-startup","info":"failed waiting for 9691, try increasing HASURA_GRAPHQL_MIGRATIONS_SERVER_TIMEOUT (default: 30)"}}
estimationapplication_graphql-engine_1 exited with code 1
```

**Comment by melehin** [comment]
@original0594 Thanks for feedback!
I fixed some issue inside fedormelexin/graphql-engine-arm64:v1.3.3.cli-migrations
Could you try it again and let's me know?
Don't forget to run **docker pull fedormelexin/graphql-engine-arm64:v1.3.3.cli-migrations** before

**Comment by original0594** [comment]
@melehin Got further with new image, fails on hasura permissions during applying migrations

```
graphql-engine_1           | time="2021-04-20T04:35:54Z" level=fatal msg="apply failed\n{\"internal\":[{\"definition\":{\"role\":\"user\",\"comment\":null,\"permission\":{\"backend_only\":false,\"set\":{},\"check\":{\"_or\":[{\"link_type\":{\"organization\":{\"users\":{\"_and\":[{\"id\":{\"_eq\":\"X-Hasura-User-Id\"}},{\"permission_level\":{\"_gte\":3}}]}}}},{\"target_project\":{\"permissions\":{\"user\":{\"permission_level\":{\"_gte\":2}}}}}]},\"columns\":[\"date\",\"id\",\"link_type_id\",\"source_project_id\",\"target_project_id\"]},\"table\":{\"schema\":\"public\",\"name\":\"project_link\"}},\"reason\":\"in table \\\"project_link\\\": in permission for role \\\"user\\\": \\\"permissions\\\" does not exist\",\"type\":\"insert_permission\"}],\"path\":\"$.args[1].args\",\"error\":\"in table \\\"project_link\\\": in permission for role \\\"user\\\": \\\"permissions\\\" does not exist\",\"code\":\"constraint-violation\"}"
estimationapplication_graphql-engine_1 exited with code 1
```

**Comment by melehin** [comment]
@original0594 
Could you try it again?

**Comment by original0594** [comment]
@melehin It works! Thank you so much! Any ideas on how to get a standalone hasura-cli running on my arm64 mac mini m1?

**Comment by melehin** [comment]
@original0594
Try to copy hasura-cli from the image
**docker cp estimationapplication_graphql-engine_1:/bin/hasura-cli hasura**
next
**./hasura**

**Comment by original0594** [comment]
@melehin returns zsh: exec format error: ./hasura

**Comment by mwarger** [comment]
@original0594 I'm able to run the regular hasura-cli without any problems.

**Comment by original0594** [comment]
@mwarger What was your install method?

**Comment by original0594** [comment]
@mwarger @melehin Figured it out! Works if installed via `npm install --global hasura-cli` , my blocker on this was i had to change the owner of my `/Usr/local/lib/node_modules` to my local user, i.e. `sudo chown -R $USER /Usr/local/lib/node_modules`. Thank you guys for all the help! Stoked to be up and running with my new machine.

**Comment by mwarger** [comment]
> @mwarger What was your install method?

I was able to install the Mac build for it.  The NPM version did not work for me after it was installed.

**Comment by etrepum** [comment]
Could you share how you are building the cli-migrations images? I'd like to try the latest v2.0.0-alpha.10.cli-migrations-v2 (and probably also v2.0.0-alpha.10.cli-migrations-v3 at some point)

**Comment by melehin** [comment]
Hi, @etrepum!
I will share a Dockerfile soon. I did it by manually before

**Comment by melehin** [comment]
@etrepum 
Could you try fedormelexin/graphql-engine-arm64:v2.0.0-alpha.10.cli-migrations-v2 or fedormelexin/graphql-engine-arm64:v2.0.0-alpha.10.cli-migrations-v3 ?

**Comment by melehin** [comment]
For build
```bash
export DOCKER_USERNAME=fedormelexin
export HASURA_VERSION=2.0.0-alpha.10
export SCRIPT_VERSION=v3
git clone https://github.com/melehin/graphql-engine-arm64 -b ghc-8.10.2
cd graphql-engine-arm64/cli-migrations
docker build --build-arg SCRIPT_VERSION=${SCRIPT_VERSION} --build-arg SERVER_IMAGE_TAG=${HASURA_VERSION} --build-arg SERVER_IMAGE=${DOCKER_USERNAME}/graphql-engine-arm64  -t "${DOCKER_USERNAME}/graphql-engine-arm64:v${HASURA_VERSION}.cli-migrations-v3" .
```

**Comment by etrepum** [comment]
@melehin so far fedormelexin/graphql-engine-arm64:v2.0.0-alpha.10.cli-migrations-v2 seems to be working perfectly, thank you! 💯 I'll try to repro the build later

**Comment by kecoco16** [comment]
Hi @melehin, first of all thanks for the work you have done here.

I am trying to use the image **fedormelexin/graphql-engine-arm64:v2.0.0-alpha.10.cli-migrations-v3** in my rpi4 but I'am getting this error
```
standard_init_linux.go:219: exec user process caused: exec format error
```

Have you seen that error before or know what may be happening?

**Comment by melehin** [comment]
Hi @kecoco16

Did you try fedormelexin/graphql-engine-arm64:v2.0.0-alpha version without cli?
And what OS distro you use?

**Comment by melehin** [comment]
@kecoco16 
I built images on rpi4 also
my uname output:
```bash
ubuntu@rpi4 [41]:~$ uname -a
Linux rpi4 5.4.0-1034-raspi #37-Ubuntu SMP PREEMPT Mon Apr 12 23:14:49 UTC 2021 aarch64 aarch64 aarch64 GNU/Linux
```
look at your uname output and aarch64 within

**Comment by kecoco16** [comment]
@melehin I have the same result running the image without the cli

My uname output is:
```
pi@raspberrypi:~ $ uname -a
Linux raspberrypi 5.10.17-v7l+ #1414 SMP Fri Apr 30 13:20:47 BST 2021 armv7l GNU/Linux
```

**Comment by kecoco16** [comment]
@melehin it seems the error is because my rpi4 is not aarch64 right?

**Comment by melehin** [comment]
@kecoco16 
right, you are using 32 bit OS distro instead of 64

**Comment by kecoco16** [comment]
Thank you @melehin, I will make the OS distro change to try again.
