### ISSUE TITLE
Docker Image for Hasura 2.0

### ISSUE THREAD

**Issue by tothda** [melehin/graphql-engine-arm64#4]
Hello!

I'm just wondering if an ARM docker image for the upcoming 2.0 release is on the roadmap? :)

Thanks for the great work!

**Comment by melehin** [comment]
Hi, @tothda!

Sure, test version 2.0.0-alpha.3 is already available on Docker Hub!
I've tested a bit of REST functionality.

https://hub.docker.com/repository/docker/fedormelexin/graphql-engine-arm64

**Comment by tothda** [comment]
Oh, very cool, thanks. I'll do some testing myself too 😉
