### ISSUE TITLE
How to access localhost for Actions and Event Handlers ?

### ISSUE THREAD

**Issue by aswinmohanme** [melehin/graphql-engine-arm64#5]
I am running the latest preview of Docker on my M1 macbook. I am also running vercel for api endpoints on `localhost:3000` on my local machine. 

How can I access this in my event handler ? I tried `http://localhost:3000/api/notifyComment`, `https://host.docker.internal:3000` but nothing seems to work. The `host.docker` seemed to work though once, is there any workaround any one has found ?

**Comment by melehin** [comment]
Hi!

Can you run it at 0.0.0.0:3000?
And try connecting to host.docker or whatever IP of your host have (exclude localhost (domain) or 127.0.0.1 (ip)).
