### ISSUE TITLE
Specifying --console-assets-dir when running the engine breaks people running cli consoles

### ISSUE THREAD

**Issue by zwily** [melehin/graphql-engine-arm64#7]
Hello,

I just switched to this arm64 image to use on my dev M1 machine, and my CLI console broke:

https://github.com/hasura/graphql-engine/issues/7030

The issue was because the arm64 image is specifying `--console-assets-dir` in the command, which tells consoles connected to use the engine for assets, but I run the engine with the console disabled since I'm using the separate CLI console (for migrations, etc). I worked around it by overriding the command (seen in that link above), but it may be nice to make the command match the official images so others don't run into this issue.

**Comment by melehin** [comment]
Hi, @zwily!

Of course, thanks for the comment!
I will update to 1.3.3, latest beta and next releases.
