### ISSUE TITLE
use the same tags as `hasura/graphql-engine`

### ISSUE THREAD

**Issue by clifton** [melehin/graphql-engine-arm64#8]
tags for `hasura/graphql-engine`  start with a `v`, e.g. `v2.0.0-beta.1` while this repo drops the v,, e.g. `2.0.0-beta.1`.  this makes for some difficulty in keeping the version of the image under version control when using an env variable

**Comment by melehin** [comment]
Hi, @clifton!

Thanks for this issue. I added tags with v.

**Comment by clifton** [comment]
Thank you!
