### ISSUE TITLE
Build for hasura 2.0.0 beta2?

### ISSUE THREAD

**Issue by deathemperor** [melehin/graphql-engine-arm64#9]
Please

**Comment by melehin** [comment]
Hi, @deathemperor!

It compiling now :)

**Comment by deathemperor** [comment]
thanks! Just need the migration image now

**Comment by melehin** [comment]
the migration image will be available today

**Comment by deathemperor** [comment]
lovely. thanks for your work @melehin

**Comment by melehin** [comment]
@deathemperor

Done.

**Comment by deathemperor** [comment]
fantastic! Thanks again.
